package com.quantlab.marketdata.connector;

import com.quantlab.marketdata.model.KlineEvent;
import com.quantlab.marketdata.model.MarketDataEvent;
import com.quantlab.marketdata.model.OrderBookSnapshotEvent;
import com.quantlab.marketdata.model.TradeEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Component;

/**
 * 基于原生 JDBC 的行情事件发布实现。
 * <p>
 * 当前阶段先避免引入更重的 ORM 或 Spring Data，
 * 直接把统一事件写入 PostgreSQL，先打通最小闭环。
 */
@Component
@Primary
@ConditionalOnProperty(prefix = "quantlab.market-data.persistence", name = "enabled", havingValue = "true")
public class JdbcMarketDataEventPublisher implements MarketDataEventPublisher {

    private static final Logger log = LoggerFactory.getLogger(JdbcMarketDataEventPublisher.class);

    private final String jdbcUrl;
    private final String username;
    private final String password;
    private final boolean postgresDialect;

    public JdbcMarketDataEventPublisher(
            @org.springframework.beans.factory.annotation.Value("${quantlab.market-data.persistence.jdbc-url}") String jdbcUrl,
            @org.springframework.beans.factory.annotation.Value("${quantlab.market-data.persistence.username}") String username,
            @org.springframework.beans.factory.annotation.Value("${quantlab.market-data.persistence.password}") String password
    ) {
        this.jdbcUrl = jdbcUrl;
        this.username = username;
        this.password = password;
        this.postgresDialect = jdbcUrl.startsWith("jdbc:postgresql:");
        initializeSchema();
    }

    @Override
    public void publish(MarketDataEvent event) {
        try (Connection connection = openConnection()) {
            switch (event) {
                case TradeEvent tradeEvent -> persistTrade(connection, tradeEvent);
                case KlineEvent klineEvent -> persistKline(connection, klineEvent);
                case OrderBookSnapshotEvent orderBookSnapshotEvent -> log.debug(
                        "Skipping order book snapshot persistence for now. exchange={}, symbol={}, updateId={}",
                        orderBookSnapshotEvent.instrument().exchange(),
                        orderBookSnapshotEvent.instrument().symbol(),
                        orderBookSnapshotEvent.updateId()
                );
            }
        } catch (SQLException exception) {
            throw new IllegalStateException("failed to persist market data event", exception);
        }
    }

    private void initializeSchema() {
        try (Connection connection = openConnection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate(
                    """
                    create table if not exists market_data_trades (
                        id bigint generated by default as identity primary key,
                        exchange_name varchar(32) not null,
                        symbol varchar(64) not null,
                        event_time timestamp with time zone not null,
                        received_at timestamp with time zone not null,
                        trade_id varchar(128) not null,
                        price numeric(36, 18) not null,
                        quantity numeric(36, 18) not null,
                        side varchar(16) not null
                    )
                    """
            );
            statement.executeUpdate(
                    """
                    create table if not exists market_data_klines (
                        id bigint generated by default as identity primary key,
                        exchange_name varchar(32) not null,
                        symbol varchar(64) not null,
                        interval_name varchar(32) not null,
                        event_time timestamp with time zone not null,
                        received_at timestamp with time zone not null,
                        open_time timestamp with time zone not null,
                        close_time timestamp with time zone not null,
                        open_price numeric(36, 18) not null,
                        high_price numeric(36, 18) not null,
                        low_price numeric(36, 18) not null,
                        close_price numeric(36, 18) not null,
                        volume numeric(36, 18) not null,
                        closed boolean not null
                    )
                    """
            );
            statement.executeUpdate(
                    """
                    create unique index if not exists uq_market_data_klines_business_key
                    on market_data_klines (exchange_name, symbol, interval_name, open_time)
                    """
            );
        } catch (SQLException exception) {
            throw new IllegalStateException("failed to initialize market data schema", exception);
        }
    }

    private Connection openConnection() throws SQLException {
        return DriverManager.getConnection(jdbcUrl, username, password);
    }

    private void persistTrade(Connection connection, TradeEvent event) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                """
                insert into market_data_trades (
                    exchange_name,
                    symbol,
                    event_time,
                    received_at,
                    trade_id,
                    price,
                    quantity,
                    side
                ) values (?, ?, ?, ?, ?, ?, ?, ?)
                """
        )) {
            statement.setString(1, event.instrument().exchange().name());
            statement.setString(2, event.instrument().symbol());
            statement.setObject(3, timestamp(event.eventTime()));
            statement.setObject(4, timestamp(event.receivedAt()));
            statement.setString(5, event.tradeId());
            statement.setBigDecimal(6, event.price());
            statement.setBigDecimal(7, event.quantity());
            statement.setString(8, event.side().name());
            statement.executeUpdate();
        }
    }

    private void persistKline(Connection connection, KlineEvent event) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(klineUpsertSql())) {
            statement.setString(1, event.instrument().exchange().name());
            statement.setString(2, event.instrument().symbol());
            statement.setString(3, event.interval().name());
            statement.setObject(4, timestamp(event.eventTime()));
            statement.setObject(5, timestamp(event.receivedAt()));
            statement.setObject(6, timestamp(event.openTime()));
            statement.setObject(7, timestamp(event.closeTime()));
            statement.setBigDecimal(8, event.openPrice());
            statement.setBigDecimal(9, event.highPrice());
            statement.setBigDecimal(10, event.lowPrice());
            statement.setBigDecimal(11, event.closePrice());
            statement.setBigDecimal(12, event.volume());
            statement.setBoolean(13, event.closed());
            statement.executeUpdate();
        }
    }

    private String klineUpsertSql() {
        if (postgresDialect) {
            return """
                    insert into market_data_klines (
                        exchange_name,
                        symbol,
                        interval_name,
                        event_time,
                        received_at,
                        open_time,
                        close_time,
                        open_price,
                        high_price,
                        low_price,
                        close_price,
                        volume,
                        closed
                    ) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    on conflict (exchange_name, symbol, interval_name, open_time)
                    do update set
                        event_time = excluded.event_time,
                        received_at = excluded.received_at,
                        close_time = excluded.close_time,
                        open_price = excluded.open_price,
                        high_price = excluded.high_price,
                        low_price = excluded.low_price,
                        close_price = excluded.close_price,
                        volume = excluded.volume,
                        closed = excluded.closed
                    """;
        }
        return """
                merge into market_data_klines (
                    exchange_name,
                    symbol,
                    interval_name,
                    event_time,
                    received_at,
                    open_time,
                    close_time,
                    open_price,
                    high_price,
                    low_price,
                    close_price,
                    volume,
                    closed
                ) key (exchange_name, symbol, interval_name, open_time)
                values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """;
    }

    private OffsetDateTime timestamp(Instant instant) {
        return instant.atOffset(ZoneOffset.UTC);
    }
}
